M1 = int(input("Enter the marks of Student - 1 : "))
M2 = int(input("Enter the marks of Student - 2 : "))
M3 = int(input("Enter the marks of Student - 3 : "))
M4 = int(input("Enter the marks of Student - 4 : "))
M5 = int(input("Enter the marks of Student - 5 : "))
M6 = int(input("Enter the marks of Student - 6 : "))
Marks = [M1, M2, M3, M4, M5, M6]
print(Marks)
Marks.sort()
print(Marks)